/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on Dec 19, 2008, 3:33:32 PM
 */

package ihmprojet2.IHM;

/**
 *
 * @author gcarrier
 */
public class MainWindow extends javax.swing.JFrame {

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        climatRBgroup = new javax.swing.ButtonGroup();
        plante1group = new javax.swing.ButtonGroup();
        plante2group = new javax.swing.ButtonGroup();
        splitter = new javax.swing.JSplitPane();
        prefsPanels = new javax.swing.JTabbedPane();
        plantesPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        temperatureLabel1 = new javax.swing.JLabel();
        temperatureLabel2 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        climatPanel = new javax.swing.JPanel();
        obscuriteRB = new javax.swing.JRadioButton();
        indirectRB = new javax.swing.JRadioButton();
        directRB = new javax.swing.JRadioButton();
        temperatureLabel = new javax.swing.JLabel();
        temperatureSlider = new javax.swing.JSlider();
        terrePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSlider3 = new javax.swing.JSlider();
        eauPanel = new javax.swing.JPanel();
        joursArrosageSlider = new javax.swing.JSlider();
        joursArrosageLabel = new javax.swing.JLabel();
        dureteLabel = new javax.swing.JLabel();
        quantiteEauLabel = new javax.swing.JLabel();
        quantiteEauSlider = new javax.swing.JSlider();
        dureteSlider = new javax.swing.JSlider();
        vuePanel = new javax.swing.JPanel();
        finalPanel = new javax.swing.JPanel();
        semainePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitter.setDividerLocation(200);
        splitter.setName("splitter"); // NOI18N

        prefsPanels.setName("prefsPanels"); // NOI18N

        plantesPanel.setName("plantesPanel"); // NOI18N

        plante1group.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Cacaï");
        jRadioButton1.setName("jRadioButton1"); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        plante1group.add(jRadioButton2);
        jRadioButton2.setText("Tomatito");
        jRadioButton2.setName("jRadioButton2"); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        temperatureLabel1.setFont(temperatureLabel1.getFont().deriveFont(temperatureLabel1.getFont().getStyle() | java.awt.Font.BOLD));
        temperatureLabel1.setText("Plante 1");
        temperatureLabel1.setName("temperatureLabel1"); // NOI18N

        temperatureLabel2.setFont(temperatureLabel2.getFont().deriveFont(temperatureLabel2.getFont().getStyle() | java.awt.Font.BOLD));
        temperatureLabel2.setText("Plante 2");
        temperatureLabel2.setName("temperatureLabel2"); // NOI18N

        plante2group.add(jRadioButton3);
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Cacaï");
        jRadioButton3.setName("jRadioButton3"); // NOI18N
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        plante2group.add(jRadioButton4);
        jRadioButton4.setText("Tomatito");
        jRadioButton4.setName("jRadioButton4"); // NOI18N
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plantesPanelLayout = new javax.swing.GroupLayout(plantesPanel);
        plantesPanel.setLayout(plantesPanelLayout);
        plantesPanelLayout.setHorizontalGroup(
            plantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plantesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temperatureLabel1)
                    .addGroup(plantesPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(plantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)))
                    .addComponent(temperatureLabel2)
                    .addGroup(plantesPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(plantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton3))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        plantesPanelLayout.setVerticalGroup(
            plantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plantesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(temperatureLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temperatureLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        prefsPanels.addTab("Plantes", plantesPanel);

        climatPanel.setName("climatPanel"); // NOI18N

        climatRBgroup.add(obscuriteRB);
        obscuriteRB.setSelected(true);
        obscuriteRB.setText("Obscurité");
        obscuriteRB.setName("obscuriteRB"); // NOI18N

        climatRBgroup.add(indirectRB);
        indirectRB.setText("Lumière indirecte");
        indirectRB.setName("indirectRB"); // NOI18N

        climatRBgroup.add(directRB);
        directRB.setText("Lumière directe");
        directRB.setName("directRB"); // NOI18N

        temperatureLabel.setFont(temperatureLabel.getFont().deriveFont(temperatureLabel.getFont().getStyle() | java.awt.Font.BOLD));
        temperatureLabel.setText("Température");
        temperatureLabel.setName("temperatureLabel"); // NOI18N

        temperatureSlider.setMajorTickSpacing(10);
        temperatureSlider.setMaximum(30);
        temperatureSlider.setMinorTickSpacing(1);
        temperatureSlider.setPaintLabels(true);
        temperatureSlider.setPaintTicks(true);
        temperatureSlider.setSnapToTicks(true);
        temperatureSlider.setName("temperatureSlider"); // NOI18N

        javax.swing.GroupLayout climatPanelLayout = new javax.swing.GroupLayout(climatPanel);
        climatPanel.setLayout(climatPanelLayout);
        climatPanelLayout.setHorizontalGroup(
            climatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(climatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(climatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obscuriteRB)
                    .addComponent(indirectRB)
                    .addComponent(directRB)
                    .addComponent(temperatureLabel)
                    .addComponent(temperatureSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addContainerGap())
        );
        climatPanelLayout.setVerticalGroup(
            climatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(climatPanelLayout.createSequentialGroup()
                .addComponent(obscuriteRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indirectRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(directRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temperatureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temperatureSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        prefsPanels.addTab("Climat", climatPanel);

        terrePanel.setName("terrePanel"); // NOI18N

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel2.setText("Quantité");
        jLabel2.setName("jLabel2"); // NOI18N

        jCheckBox1.setText("Engrais");
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        jSlider3.setMajorTickSpacing(100);
        jSlider3.setMaximum(500);
        jSlider3.setMinimum(100);
        jSlider3.setMinorTickSpacing(10);
        jSlider3.setPaintLabels(true);
        jSlider3.setPaintTicks(true);
        jSlider3.setSnapToTicks(true);
        jSlider3.setName("jSlider3"); // NOI18N

        javax.swing.GroupLayout terrePanelLayout = new javax.swing.GroupLayout(terrePanel);
        terrePanel.setLayout(terrePanelLayout);
        terrePanelLayout.setHorizontalGroup(
            terrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(terrePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(terrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        terrePanelLayout.setVerticalGroup(
            terrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(terrePanelLayout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );

        prefsPanels.addTab("Terre", terrePanel);

        eauPanel.setName("eauPanel"); // NOI18N

        joursArrosageSlider.setMajorTickSpacing(1);
        joursArrosageSlider.setMaximum(7);
        joursArrosageSlider.setMinimum(1);
        joursArrosageSlider.setPaintLabels(true);
        joursArrosageSlider.setPaintTicks(true);
        joursArrosageSlider.setSnapToTicks(true);
        joursArrosageSlider.setName("joursArrosageSlider"); // NOI18N

        joursArrosageLabel.setFont(joursArrosageLabel.getFont().deriveFont(joursArrosageLabel.getFont().getStyle() | java.awt.Font.BOLD));
        joursArrosageLabel.setText("Jours d'arrosage");
        joursArrosageLabel.setName("joursArrosageLabel"); // NOI18N

        dureteLabel.setFont(dureteLabel.getFont().deriveFont(dureteLabel.getFont().getStyle() | java.awt.Font.BOLD));
        dureteLabel.setText("Dureté");
        dureteLabel.setName("dureteLabel"); // NOI18N

        quantiteEauLabel.setFont(quantiteEauLabel.getFont().deriveFont(quantiteEauLabel.getFont().getStyle() | java.awt.Font.BOLD));
        quantiteEauLabel.setText("Quantité");
        quantiteEauLabel.setName("quantiteEauLabel"); // NOI18N

        quantiteEauSlider.setMajorTickSpacing(100);
        quantiteEauSlider.setMaximum(500);
        quantiteEauSlider.setMinorTickSpacing(10);
        quantiteEauSlider.setPaintLabels(true);
        quantiteEauSlider.setPaintTicks(true);
        quantiteEauSlider.setSnapToTicks(true);
        quantiteEauSlider.setValue(500);
        quantiteEauSlider.setName("quantiteEauSlider"); // NOI18N

        dureteSlider.setMajorTickSpacing(1);
        dureteSlider.setMaximum(5);
        dureteSlider.setMinimum(1);
        dureteSlider.setPaintLabels(true);
        dureteSlider.setPaintTicks(true);
        dureteSlider.setSnapToTicks(true);
        dureteSlider.setName("dureteSlider"); // NOI18N

        javax.swing.GroupLayout eauPanelLayout = new javax.swing.GroupLayout(eauPanel);
        eauPanel.setLayout(eauPanelLayout);
        eauPanelLayout.setHorizontalGroup(
            eauPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eauPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eauPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(joursArrosageSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(joursArrosageLabel)
                    .addComponent(quantiteEauLabel)
                    .addComponent(dureteLabel)
                    .addComponent(dureteSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(quantiteEauSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addContainerGap())
        );
        eauPanelLayout.setVerticalGroup(
            eauPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eauPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(joursArrosageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joursArrosageSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantiteEauLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantiteEauSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dureteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dureteSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        prefsPanels.addTab("Eau", eauPanel);

        splitter.setLeftComponent(prefsPanels);

        vuePanel.setName("vuePanel"); // NOI18N
        vuePanel.setLayout(new javax.swing.BoxLayout(vuePanel, javax.swing.BoxLayout.Y_AXIS));

        finalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Après une semaine"));
        finalPanel.setName("finalPanel"); // NOI18N

        javax.swing.GroupLayout finalPanelLayout = new javax.swing.GroupLayout(finalPanel);
        finalPanel.setLayout(finalPanelLayout);
        finalPanelLayout.setHorizontalGroup(
            finalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );
        finalPanelLayout.setVerticalGroup(
            finalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        vuePanel.add(finalPanel);

        semainePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Jour par jour"));
        semainePanel.setName("semainePanel"); // NOI18N

        javax.swing.GroupLayout semainePanelLayout = new javax.swing.GroupLayout(semainePanel);
        semainePanel.setLayout(semainePanelLayout);
        semainePanelLayout.setHorizontalGroup(
            semainePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );
        semainePanelLayout.setVerticalGroup(
            semainePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        vuePanel.add(semainePanel);

        splitter.setRightComponent(vuePanel);

        getContentPane().add(splitter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel climatPanel;
    private javax.swing.ButtonGroup climatRBgroup;
    private javax.swing.JRadioButton directRB;
    private javax.swing.JLabel dureteLabel;
    private javax.swing.JSlider dureteSlider;
    private javax.swing.JPanel eauPanel;
    private javax.swing.JPanel finalPanel;
    private javax.swing.JRadioButton indirectRB;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JLabel joursArrosageLabel;
    private javax.swing.JSlider joursArrosageSlider;
    private javax.swing.JRadioButton obscuriteRB;
    private javax.swing.ButtonGroup plante1group;
    private javax.swing.ButtonGroup plante2group;
    private javax.swing.JPanel plantesPanel;
    private javax.swing.JTabbedPane prefsPanels;
    private javax.swing.JLabel quantiteEauLabel;
    private javax.swing.JSlider quantiteEauSlider;
    private javax.swing.JPanel semainePanel;
    private javax.swing.JSplitPane splitter;
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JLabel temperatureLabel1;
    private javax.swing.JLabel temperatureLabel2;
    private javax.swing.JSlider temperatureSlider;
    private javax.swing.JPanel terrePanel;
    private javax.swing.JPanel vuePanel;
    // End of variables declaration//GEN-END:variables

}
